- name: Initial configuration
  tags: initial configuration
  hosts: all
  become: true
  tasks:
    - name: disable default route
      tags: change def route
      ansible.builtin.template:
        src: templates/haproxy-ext/01-netcfg.yaml
        dest: /etc/netplan/01-netcfg.yaml
        owner: root
        group: root
        mode: 0600
      notify: netplan apply

    - name: add static routers to hosts
      tags: change def route
      ansible.builtin.template:
        src: templates/haproxy-ext/50-vagrant.yaml.j2
        dest: /etc/netplan/50-vagrant.yaml
        owner: root
        group: root
        mode: 0600
      notify: netplan apply

    - name: remove 50-cloud-init.yaml
      tags: change def route
      ansible.builtin.file:
        path: /etc/netplan/50-cloud-init.yaml
        state: absent
      notify: netplan apply

    - name: Add lines to /etc/hosts
      tags: setup hosts
      ansible.builtin.blockinfile:
        dest: /etc/hosts
        block: |
          192.168.56.10 haproxy-ext-1
          192.168.56.10 haproxy-ext-2
        state: present

    - name: Disable ufw service
      ansible.builtin.service:
        name: ufw
        state: stopped
        enabled: false

    - name: Set timezone to Europe/Moscow
      community.general.timezone:
        name: Europe/Moscow

    - name: Uninstall 'ntp' package
      ansible.builtin.apt:
        name: ntp
        state: absent

    - name: Turning "set-ntp" on
      command: /usr/bin/timedatectl set-ntp on

  handlers:
    - name: netplan apply
      command: netplan apply

# ========================================

- name: Set up haproxy and keepalived
  tags: setup balancer
  hosts: all
  become: true
  tasks:
    - name: Install haproxy
      tags: install haproxy
      ansible.builtin.apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Install keepalived
      tags: install keepalived
      ansible.builtin.apt:
        name: keepalived
        state: present
        update_cache: yes

    - name: Copy haproxy config
      tags: copy haproxy config
      ansible.builtin.template:
        src: templates/haproxy-ext/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
      notify: restart haproxy

    - name: Copy keepalived config
      tags: copy keepalived config
      ansible.builtin.template:
        src: templates/haproxy-ext/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
      notify: restart keepalived

  handlers:
    - name: restart haproxy
      ansible.builtin.service:
        name: haproxy
        state: restarted

    - name: restart keepalived
      ansible.builtin.service:
        name: keepalived
        state: restarted
