- name: Initial configuration
  tags: initial configuration
  hosts: haproxy-int
  become: true
  tasks:
    - name: Check host availability
      ansible.builtin.ping:

    - name: Add lines to /etc/hosts
      tags: setup hosts
      ansible.builtin.blockinfile:
        dest: /etc/hosts
        block: |
          192.168.56.10 haproxy-ext-1
          192.168.56.11 haproxy-ext-2
          192.168.56.20 haproxy-int
          192.168.56.21 haproxy-int-1
          192.168.56.22 haproxy-int-2
          192.168.56.31 control-1
          192.168.56.32 control-2
          192.168.56.33 control-3
          192.168.56.41 node-1
          192.168.56.42 node-2
          192.168.56.43 node-3
          192.168.56.51 database-1
          192.168.56.52 database-2
          192.168.56.53 database-3
        state: present

    - name: Disable ufw service
      ansible.builtin.service:
        name: ufw
        state: stopped
        enabled: false

    - name: Set timezone to Europe/Moscow
      community.general.timezone:
        name: Europe/Moscow

    - name: Uninstall 'ntp' package
      ansible.builtin.apt:
        name: ntp
        state: absent

    - name: Turning "set-ntp" on
      command: /usr/bin/timedatectl set-ntp on

# ========================================

- name: Set up haproxy and keepalived
  tags: setup haproxy-int
  hosts: haproxy-int
  become: true
  tasks:
    - name: Install haproxy
      tags: install haproxy
      ansible.builtin.apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Copy haproxy config
      tags: copy haproxy config
      ansible.builtin.template:
        src: templates/haproxy-int/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
      notify: restart haproxy

    - name: Install keepalived
      tags: install keepalived
      ansible.builtin.apt:
        name: keepalived
        state: present
        update_cache: yes

    - name: Copy keepalived config
      tags: copy keepalived config
      ansible.builtin.template:
        src: templates/haproxy-int/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
      notify: restart keepalived

  handlers:
    - name: restart haproxy
      ansible.builtin.service:
        name: haproxy
        state: restarted

    - name: restart keepalived
      ansible.builtin.service:
        name: keepalived
        state: restarted
