- name: Setup Nextcloud
  tags: setup nextcloud
  hosts: control-1
  become: true
  tasks:
    - name: Create database for nextcloud
      tags: create database for nextcloud
      ansible.builtin.shell: "PGPASSWORD=OtusHL psql -Upostgres -h192.168.56.20 -p5000 < /vagrant/templates/postgresql/nextcloud.sql"

    - name: Add Nextcloud helm repo
      tags: add nextcloud repo
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "https://nextcloud.github.io/helm/"
      ignore_errors: true

    - name: Deploy Nextcloud chart using values files
      tags: deploy nextcloud
      kubernetes.core.helm:
        name: nextcloud
        chart_ref: nextcloud/nextcloud
        release_namespace: nextcloud
        create_namespace: true
        update_repo_cache: true
        values_files:
          - /vagrant/kubernetes/values-nextcloud.yaml
